dist: trusty

language: python

python:
    - 3.6
before_install:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env

install:
    - poetry install

script:
    - pytest -v
    - black --check --verbose src/

