dist: trusty

language: python

stages:
    - linting
    - test

python:
    - 3.6

before_install:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - source $HOME/.poetry/env

install:
    - poetry install

script:
    - pytest -v
    - black --check --verbose src/


jobs:
  include:
    - python: "3.6"

    - stage: linting
      python: "3.6"
      install:
        - pip install pre-commit
        - pre-commit install-hooks
      script:
        - pre-commit run --all-files
